name: ${PROJECT_NAME}

include:
  - path:
      - ../.devcontainer/compose/compose.devcontainer.${PLATFORM}.yaml

services:
  cross_domain_router:
    extends:
      file: ../.devcontainer/compose/compose.fast_dds_router.yaml
      service: fast_dds_router
    volumes:
      - type: bind
        source: ../.devcontainer/config/cross_domain_fast_dds_router_config.yaml
        target: /fast_dds_router_config.yaml
        read_only: true
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
