name: ${PROJECT_NAME}

include:
  - path:
      - ../.devcontainer/compose/compose.devcontainer.${PLATFORM}.yaml
      - ../.devcontainer/compose/compose.cross_domain_router.yaml

services:
  ntp_server_for_create_3:
    image: dockurr/chrony
    environment:
      - NTP_SERVERS=${NTP_SERVER}
    network_mode: host