FROM isaac-ros AS tb4

WORKDIR ${HOME}/dependencies

# DepthAI ROS
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-depthai-ros && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# iRobot Create
RUN sudo apt update && sudo apt install -y \
        curl \
        gnupg2 \
        lsb-release && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    sudo curl -sSL "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key" -o "/usr/share/keyrings/ros-archive-keyring.gpg" && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee -a "/etc/apt/sources.list.d/ros2.list"

RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-irobot-create-msgs && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* 

# Livox SDK2
RUN git clone -b "v1.2.5" --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    mkdir "build" && cd "build" && \
    cmake ".." && \
    make -j$(nproc) && \
    sudo make install

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    rosdep update && \
    git clone -b "main" --depth 1 "https://gitlab+deploy-token-28:gldt-Fnui4V-UxTzsHFDmgarX@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/livox-ros-driver-2.git" "livox_ros_driver_2" && \
    cd "livox_ros_driver_2" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

# Isaac ROS packages
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
        ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
        ros-${ROS_DISTRO}-isaac-ros-jetson-stats && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

RUN sudo rm -rf "${HOME}/dependencies"

WORKDIR ${WORKSPACE_DIRECTORY}

# Turtlebot4 packages
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-turtlebot4-description \
        ros-${ROS_DISTRO}-turtlebot4-msgs \
        ros-${ROS_DISTRO}-turtlebot4-navigation \
        ros-${ROS_DISTRO}-turtlebot4-node && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

RUN mkdir -p "${WORKSPACE_DIRECTORY}/turtlebot4_ws/src" && cd "${WORKSPACE_DIRECTORY}/turtlebot4_ws/src" && \
    git clone -b "${ROS_DISTRO}" --depth 1 "https://github.com/turtlebot/turtlebot4.git" && \
    git clone -b "${ROS_DISTRO}" --depth 1 "https://github.com/turtlebot/turtlebot4_robot.git" 

RUN cd "${WORKSPACE_DIRECTORY}/turtlebot4_ws" && \
    rosdep update && \
    rosdep install --from-paths "src" -yi --rosdistro ${ROS_DISTRO}

RUN source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    cd "${WORKSPACE_DIRECTORY}/turtlebot4_ws" && \
    colcon build --symlink-install

RUN echo "source ${WORKSPACE_DIRECTORY}/turtlebot4_ws/install/setup.bash" >> "/etc/bash.bashrc"

CMD "${REPOSITORY_DIRECTORY}/.devcontainer/scripts/post_start_command" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    cd "${REPOSITORY_DIRECTORY}/colcon_ws" && \
    colcon build --symlink-install && \
    source "install/setup.bash" && \
    ros2 launch sfg_tb4 "tb4.launch.py"
