FROM isaac-ros AS tb4

WORKDIR "${WORKSPACE_DIRECTORY}/dependencies"

# DepthAI ROS
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-depthai-ros && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*"

# iRobot Create
RUN sudo apt update && sudo apt install -y \
        curl \
        gnupg2 \
        lsb-release && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*" && \
    sudo curl -sSL "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key" -o "/usr/share/keyrings/ros-archive-keyring.gpg" && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee -a "/etc/apt/sources.list.d/ros2.list"

RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-irobot-create-msgs && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*" 

# Livox SDK2
RUN git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    mkdir "build" && cd "build" && \
    cmake ".." && \
    make -j$(nproc) && \
    sudo make install

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*" && \
    \
    git clone "https://github.com/Livox-SDK/livox_ros_driver2.git" && cd "livox_ros_driver2" && \
    # This package tries to aim for compatibility with ROS1 and ROS2 and (as a result) fails
    # to integrate seamlessly with the ROS build system. So we need to fix the package.xml...
    mv "package_ROS2.xml" "package.xml" && \
    # and the CMakeLists.txt.
    sed -i 's/if(HUMBLE_ROS STREQUAL "humble")/if(DEFINED ENV{ROS_DISTRO} AND $ENV{ROS_DISTRO} STREQUAL "humble")/' "CMakeLists.txt" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y ./*.deb && rm ./*.deb


# Isaac ROS packages
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
        ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
        ros-${ROS_DISTRO}-isaac-ros-jetson-stats && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*"

RUN sudo rm -rf "${WORKSPACE_DIRECTORY}/dependencies"

WORKDIR "${WORKSPACE_DIRECTORY}"

# Turtlebot4 packages
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-humble-turtlebot4-description \
        ros-humble-turtlebot4-msgs \
        ros-humble-turtlebot4-navigation \
        ros-humble-turtlebot4-node
        
RUN mkdir -p ${WORKSPACE_DIRECTORY}/turtlebot4_ws/src && \
    cd ${WORKSPACE_DIRECTORY}/turtlebot4_ws/src && \
    git clone https://github.com/turtlebot/turtlebot4.git -b humble && \
    git clone https://github.com/turtlebot/turtlebot4_robot.git 

RUN cd ${WORKSPACE_DIRECTORY}/turtlebot4_ws && \
    rosdep update && \
    rosdep install --from-path src -yi --rosdistro humble

RUN /bin/bash -c "source /opt/ros/humble/setup.bash && \
    cd ${WORKSPACE_DIRECTORY}/turtlebot4_ws && \
    colcon build --symlink-install"

RUN echo "source ${WORKSPACE_DIRECTORY}/turtlebot4_ws/install/setup.bash" >> ~/.bashrc


