FROM sfg-agent-devcontainer AS sfg-tb4

WORKDIR ${HOME}/dependencies

# iRobot Create
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-irobot-create-msgs && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# Teleop Controller
RUN sudo apt update &&  sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-joy-linux  \
        ros-${ROS_DISTRO}-teleop-twist-joy && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# DepthAI ROS
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-depthai-ros && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"*

# Livox SDK2
RUN git clone -b "v1.2.5" --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    cmake -B "build" \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build "build" -j$(nproc) && \
    sudo cmake --install "build" && sudo ldconfig

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/"* && \
    \
    rosdep update && \
    git clone -b "main" --depth 1 "https://gitlab+deploy-token-28:gldt-Fnui4V-UxTzsHFDmgarX@gitlab.hs-esslingen.de/smart-factory-grids/autonomous-systems/tools/livox-ros-driver-2.git" "livox_ros_driver_2" && \
    cd "livox_ros_driver_2" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y "./"*".deb" && rm "./"*".deb" && \
    sudo rm -rf "${HOME}/.ros/rosdep/"*

RUN sudo rm -rf "${HOME}/dependencies"

WORKDIR ${WORKSPACE_DIRECTORY}

CMD "${REPOSITORY_DIRECTORY}/.devcontainer/scripts/post_start_command" && \
    source "/opt/ros/${ROS_DISTRO}/setup.bash" && \
    cd "${REPOSITORY_DIRECTORY}/colcon_ws" && \
    source "install/setup.bash" && \
    ros2 launch sfg_tb4_bringup "bringup.launch.py"