#!/usr/bin/env bash

sfg_tb4__set_up_udev_rules() {
    local SCRIPT_DIR
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/../.devcontainer/scripts/bash_utils/print_utils"

    local START_TEXT="> Setting up udev rules."
    local END_TEXT="< Done setting up udev rules."

    sfg_bash_utils__print_info "${START_TEXT}"
    local OAKD_PRO_UDEV_FILE="/etc/udev/rules.d/80-movidius.rules"

    if [ ! -f ${OAKD_PRO_UDEV_FILE} ]; then
        sfg_bash_utils__print_plain "Adding udev rules for OAK-D Pro."
        echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | sudo tee "${OAKD_PRO_UDEV_FILE}" >"/dev/null"
        sudo udevadm control --reload-rules && sudo udevadm trigger
    fi

    sfg_bash_utils__print_info "${END_TEXT}"
}

sfg_tb4__configure_interface() {
    local connection_type="${1}"
    local connection_name="${2}"
    local interface_name="${3}"
    local args=("${@:4}")

    local SCRIPT_DIR
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/../.devcontainer/scripts/bash_utils/print_utils"

    local start_text="> Setting up ${interface_name} ethernet interface for connection to ${connection_name}."
    local end_text="< Done setting up ${interface_name} ethernet interface for connection to ${connection_name}."

    sfg_bash_utils__print_info "${start_text}"

    if ! nmcli connection show "${connection_name}" >"/dev/null" 2>&1; then
        sudo nmcli connection add \
            type "${connection_type}" \
            con-name "${connection_name}" \
            ifname "${interface_name}" \
            "${args[@]}"
        sudo nmcli connection up "${connection_name}"
    else
        sfg_bash_utils__print_plain "Connection already exists. Nothing needs to be done."
    fi
    
    sfg_bash_utils__print_info "${end_text}"
}

sfg_tb4__initialize_command() {
    local SCRIPT_DIR
    SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
    source "${SCRIPT_DIR}/../fast_dds_router/.devcontainer/scripts/initialize_command"
    sfg_tb4__set_up_udev_rules "${@}"
    sfg_tb4__configure_interface "ethernet" "lidar" "enP8p1s0" "ip4" "192.168.1.18/24" "ipv4.method" "manual"
    sfg_fast_dds_router__initialize_command LOCAL_WORKSPACE_DIRECTORY="${SCRIPT_DIR}/../fast_dds_router" CONTAINER_WORKSPACE_DIRECTORY="/workspaces"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    sfg_tb4__initialize_command "${@}"
fi
