#!/usr/bin/env bash
#!/usr/bin/env bash
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)

source "${SCRIPT_DIR}/../.devcontainer/scripts/print_utils"

find_ethernet_interface() {
    local bus_type="$1"
    local found_interfaces=()

    print_plain "Attempting to identify ${bus_type}-based ethernet interface..."

    for interface in "/sys/class/net/"*; do
        local interface_name=$(basename "${interface}")

        local device_link="${interface}/device"

        # Skip if it's not a physical device, i.e. skip virtual or non-MAC devices.
        if [[ ! -L "${device_link}" || ! -f "${interface}/address" ]]; then
            continue
        fi

        # Resolve the device path.
        local device_path=$(readlink -f "${device_link}")

        # Skip device if it's not of the requested bus type.
        if ! echo "${device_path}" | grep -q "/${bus_type,,}"; then
            continue
        fi

        # Skip non-ethernet devices.
        if ! ip link show dev "${interface_name}" | grep -qw "link/ether"; then
            continue
        fi

        # Skip wireless devices.
        if [[ -d "${interface}/wireless" ]]; then
            continue
        fi

        found_interfaces+=("${interface_name}")
    done

    if [[ ${#found_interfaces[@]} -eq 0 ]]; then
        print_error "Failed to find a suitable ${bus_type} ethernet interface."
        return 1
    fi

    if [[ ${#found_interfaces[@]} -gt 1 ]]; then
        print_warning "Found multiple potential ${bus_type} ethernet interfaces: $(printf '%s, ' "${found_interfaces[@]}" | sed 's/, $//'). Using ${found_interfaces[0]}."
    else
        print_plain "Found ${bus_type} ethernet interface ${found_interfaces[0]}."
    fi

    echo "${found_interfaces[0]}"
    return 0
}

rename_interface() {
    local interface_name="${1}"
    local target_interface_name="${2}"

    if ! sudo ip link show "${interface_name}" | grep -q "${target_interface_name}"; then
        sudo ip link set "${interface_name}" down

        # Rename the interface.
        if ! sudo ip link set "${interface_name}" name "${target_interface_name}"; then
            print_error "Failed to rename interface to ${target_interface_name}."
            return 1
        fi

        print_plain "Renamed interface to ${target_interface_name}."
        interface_name=${target_interface_name}
    else
        print_plain "Interface is already named ${target_interface_name}."
    fi
}

configure_ethernet_interface() {
    local interface_name="${1}"
    local ip_address="${2}"
    local target_interface_name="$3"

    if [[ -z "${interface_name}" ]]; then
        print_error "Could not reliably identify an interface."
        return 1
    fi

    # Check if IP already exists before adding.
    if ! sudo ip addr show dev "${interface_name}" | grep -q "inet ${ip_address}"; then
        sudo ip link set "${interface_name}" down

        # Add IP address to the interface.
        if ! sudo ip addr add "${ip_address}" dev "${interface_name}"; then
            print_error "Failed to add IP ${ip_address} to ${interface_name}."
            return 1
        fi

        print_plain "Added IP address ${ip_address} to interface ${interface_name}."
    else
        print_plain "IP address ${ip_address} already exists on interface ${interface_name}."
    fi

    if rename_interface "${interface_name}" "${target_interface_name}"; then
        interface_name="${target_interface_name}"
    fi

    # Bring the interface up.
    if ! sudo ip link set "${interface_name}" up; then
        print_error "Failed to bring up interface ${interface_name}."
        return 1
    fi

    return 0
}

set_up_lidar_interface() {
    local START_TEXT="> Setting up lidar ethernet interface."
    local END_TEXT="< Done setting up lidar ethernet interface."

    print_info "${START_TEXT}"
    local target_interface_ip="192.168.1.18/24"
    local interface_name=$(find_ethernet_interface "PCI" "lidar")
    configure_ethernet_interface "${interface_name}" "${target_interface_ip}" "lidar"
    print_info "${END_TEXT}"
}

set_up_lidar_interface
