#include <rclcpp_components/register_node_macro.hpp>

#include "sfg_tb4_hardware_interface/locomotion_controller.hpp"

RCLCPP_COMPONENTS_REGISTER_NODE(sfg_tb4_hardware_interface::LocomotionController)