/**:
  ros__parameters:
    color_resolution: 1080p
    depth_resolution: 720p
    fps: 15
    frame_id: camera_head

    .camera_head.depth.image_raw.compressedDepth.format: rvl
    .camera_head.color.image_raw.ffmpeg.encoding: h264_nvmpi
    .camera_head.color.image_raw.ffmpeg.preset: ultrafast

    camera_head.depth.image_raw.enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/raw
    camera_head.color.image_raw.enable_pub_plugins:
      - image_transport/ffmpeg
      - image_transport/raw
