FROM devcontainer AS tb4

# dockerfile-utils: ignore
WORKDIR "${WORKSPACE_DIRECTORY}/dependencies"

# Livox SDK2
RUN git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git" && \
    cd "Livox-SDK2" && \
    mkdir "build" && cd "build" && \
    cmake ".." && \
    make -j$(nproc) && \
    sudo make install

# Livox ROS Driver 2
RUN sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-pcl-conversions && \
    \
    git clone "https://github.com/Livox-SDK/livox_ros_driver2.git" && cd "livox_ros_driver2" && \
    # This package tries to aim for compatibility with ROS1 and ROS2 and (as a result) fails
    # to integrate seamlessly with the ROS build system. So we need to fix the package.xml...
    mv "package_ROS2.xml" "package.xml" && \
    # and the CMakeLists.txt.
    sed -i 's/if(HUMBLE_ROS STREQUAL "humble")/if(DEFINED ENV{ROS_DISTRO} AND $ENV{ROS_DISTRO} STREQUAL "humble")/' "CMakeLists.txt" && \
    # Generate debian files.
    bloom-generate rosdebian && \
    # Use all cores for building.
    sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules" && \
    # Ignore missing info for shlibdeps if applicable.
    sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules" && \
    # Build the package.
    fakeroot "debian/rules" binary && \
    # Install the package.
    cd ".." && sudo apt install -y ./*.deb && rm ./*.deb

# Add the Open Robotics GPG key and ROS 2 repository
RUN sudo apt update && sudo apt install -y curl gnupg2 lsb-release && \
    sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/ros2.list && \
    sudo apt update


# Isaac ROS packages
RUN --mount=type=cache,id=apt_cache_devcontainer,target="/var/cache/apt" \
    sudo apt update && sudo apt install -y --no-install-recommends \
        ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
        ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
        ros-${ROS_DISTRO}-isaac-ros-jetson-stats \
        ros-${ROS_DISTRO}-irobot-create-msgs \
        ros-${ROS_DISTRO}-depthai-ros && \
    sudo apt -y autoremove && sudo apt clean && sudo rm -rf "/var/lib/apt/lists/*"

RUN sudo rm -rf "${WORKSPACE_DIRECTORY}/dependencies"

WORKDIR "${WORKSPACE_DIRECTORY}"
    
