#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e
# Create dedicated directory for dependencies.
mkdir -p "${HOME}/dependencies"

# Livox SDK2
cd "${HOME}/dependencies"
git clone --depth 1 "https://github.com/Livox-SDK/Livox-SDK2.git"
cd "Livox-SDK2"
mkdir "build" && cd "build"
cmake ".."
make -j$(nproc)
sudo make install

# Livox ROS Driver 2
sudo apt update && sudo apt install -y --no-install-recommends \
    ros-${ROS_DISTRO}-pcl-conversions

cd "${HOME}/dependencies"
git clone "https://github.com/Livox-SDK/livox_ros_driver2.git" && cd "livox_ros_driver2"
# This package tries to aim for compatibility with ROS1 and ROS2 and (as a result) fails
# to integrate seamlessly with the ROS build system. So we need to fix the package.xml...
mv "package_ROS2.xml" "package.xml"
# and the CMakeLists.txt.
sed -i 's/if(HUMBLE_ROS STREQUAL "humble")/if(DEFINED ENV{ROS_DISTRO} AND $ENV{ROS_DISTRO} STREQUAL "humble")/' "CMakeLists.txt"
# Generate debian files.
bloom-generate rosdebian
# Use all cores for building.
sed -i 's/\bdh_auto_build\b/& -- -j$(nproc)/g' "debian/rules"
# Ignore missing info for shlibdeps if applicable.
sed -i 's/dh_shlibdeps -/dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info -/g' "debian/rules"
# Build the package.
fakeroot "debian/rules" binary
# Install the package.
cd ".." && sudo apt-get install -y ./*.deb && rm ./*.deb

# Add the Open Robotics GPG Repo to the sources list
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
sudo apt update 

# Isaac ROS packages
sudo apt update && sudo apt install -y --no-install-recommends \
    ros-${ROS_DISTRO}-isaac-ros-h264-decoder \
    ros-${ROS_DISTRO}-isaac-ros-h264-encoder \
    ros-${ROS_DISTRO}-isaac-ros-jetson-stats \
    ros-${ROS_DISTRO}-irobot-create-msgs

sudo rm -rf "${HOME}/dependencies"
