#!/usr/bin/env bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>"/dev/null" && pwd)
source "${SCRIPT_DIR}/../.devcontainer/scripts/print_utils"

# Exit immediately if a command exits with a non-zero status.
set -e

set_up_usb_ethernet_interface() {
    print_info "> Setting up usb ethernet interface."
    sudo bash -c 'echo "192.168.186.3" > /opt/nvidia/l4t-usb-device-mode/IP_ADDRESS_FOR_CREATE3_ROBOT.conf'
    sudo curl -o /opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime-start.sh https://iroboteducation.github.io/create3_docs/setup/data/nv-l4t-usb-device-mode-runtime-start.sh
    sudo chmod +x /opt/nvidia/l4t-usb-device-mode/nv-l4t-usb-device-mode-runtime-start.sh
    print_info "< Done setting up usb ethernet ethernet interface."
}

set_up_usb_ethernet_interface
