/**:
  ros__parameters:
    fps: 15

    # Color stream settings.
    color.resolution: 1920x1080
    color.image_raw.ffmpeg.encoder: h264_nvmpi
    color.image_raw.ffmpeg.gop_size: 1
    color.image_raw.ffmpeg.bit_rate: 3000000
    color.image_raw.ffmpeg.encoder_av_options: profile:high,preset:ultrafast
    color.image_raw.enable_pub_plugins:
      - image_transport/ffmpeg
      - image_transport/raw

    # Depth stream settings.
    depth.resolution: 1280x720
    .depth.image_raw.compressedDepth.format: rvl
    depth.image_raw.enable_pub_plugins:
      - image_transport/compressedDepth
      - image_transport/raw
