<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>sfg_tb4_bringup</name>
    <version>0.0.0</version>
    <description>The package responsible for launching the entire TurtleBot4 software stack.</description>
    <maintainer email="matthias.brandel@hs-esslingen.de">Matthias Brandel</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>rclcpp_components</exec_depend>
    <exec_depend>ros2launch</exec_depend>
    <exec_depend>sfg_agent</exec_depend>
    <exec_depend>sfg_tb4_hardware_interface</exec_depend>
    <exec_depend>sfg_utils</exec_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>