<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>sfg_tb4_hardware_interface</name>
    <version>0.0.0</version>
    <description>The TurtleBot4 package responsible for interfacing with the robot's hardware.</description>
    <maintainer email="matthias.brandel@hs-esslingen.de">Matthias Brandel</maintainer>
    <license>MIT</license>

    <depend>rclcpp</depend>
    <depend>rclcpp_components</depend>
    <depend>geometry_msgs</depend>
    <depend>sfg_agent_msgs</depend>
    <depend>sfg_utils</depend>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>livox_ros_driver2</exec_depend>
    <exec_depend>ros2launch</exec_depend>
    <exec_depend>sfg_depthai</exec_depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>